version: "3"

services:
  user-service:
    image: user-service
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user-service
    restart: always
    networks:
      - user-db-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5001
      - VIRTUAL_HOST=b6ryik-user-service.local
    depends_on:
      - user-db-service
    ports:
      - 5001:5001

  user-db-service:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: user-db
    restart: always
    environment:
      SA_PASSWORD: "YourPassword1234"
      ACCEPT_EULA: "Y"
      MSSQL_PID: Developer
    networks:
      - user-db-network
    ports:
      - 1433:1433

networks:
  user-db-network:
    driver: bridge
