version: "3.4"

services:
  schedule-service:
    image: ${DOCKER_REGISTRY-}scheduleservice
    build:
      context: schedule-service
      dockerfile: Dockerfile
    depends_on:
      - schedule-db
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=5005
    ports:
      - 5005:5005
    networks:
      - backend-network
    restart: always

  schedule-db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    environment:
      SA_PASSWORD: "YourPassword1234"
      ACCEPT_EULA: "Y"
      MSSQL_PID: Developer
    networks:
      - backend-network

networks:
  backend-network:
