// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using stock_service.Database;

#nullable disable

namespace stock_service.Migrations
{
    [DbContext(typeof(StockDbContext))]
    partial class StockDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("stock_service.Models.Stock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Unit")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Stocks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 40,
                            Name = "Burgonya",
                            Unit = 0
                        },
                        new
                        {
                            Id = 2,
                            Amount = 3,
                            Name = "Olaj",
                            Unit = 2
                        },
                        new
                        {
                            Id = 3,
                            Amount = 25,
                            Name = "Csirkemell filé",
                            Unit = 4
                        },
                        new
                        {
                            Id = 4,
                            Amount = 150,
                            Name = "Bors",
                            Unit = 1
                        },
                        new
                        {
                            Id = 5,
                            Amount = 400,
                            Name = "Csípős szósz",
                            Unit = 3
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
