version: "3"

services:
  workday-service:
    image: workday-service
    build:
      context: .
      dockerfile: Dockerfile
    container_name: workday-service
    restart: always
    networks:
      - workday-db-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5004
      - VIRTUAL_HOST=_
    depends_on:
      - workday-db-service
    ports:
      - 5004:5004

  workday-db-service:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: workday-db
    restart: always
    environment:
      SA_PASSWORD: "YourPassword1234"
      ACCEPT_EULA: "Y"
      MSSQL_PID: Developer
    networks:
      - workday-db-network
    ports:
      - 1433:1433

networks:
  workday-db-network:
    driver: bridge
