// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using schedule_service.Database;

#nullable disable

namespace schedule_service.Migrations
{
    [DbContext(typeof(ScheduleDbContext))]
    [Migration("20250117075603_InitContext")]
    partial class InitContext
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("schedule_service.Models.Schedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("From")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("To")
                        .HasColumnType("datetime2");

                    b.Property<int>("WorkdayId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Schedules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EmployeeId = "waiter-id-1",
                            From = new DateTime(2025, 1, 18, 8, 0, 0, 0, DateTimeKind.Local),
                            To = new DateTime(2025, 1, 18, 17, 30, 0, 0, DateTimeKind.Local),
                            WorkdayId = 1
                        },
                        new
                        {
                            Id = 2,
                            EmployeeId = "kitchen-id-1",
                            From = new DateTime(2025, 1, 18, 8, 0, 0, 0, DateTimeKind.Local),
                            To = new DateTime(2025, 1, 18, 17, 30, 0, 0, DateTimeKind.Local),
                            WorkdayId = 1
                        },
                        new
                        {
                            Id = 3,
                            EmployeeId = "waiter-id-1",
                            From = new DateTime(2025, 1, 19, 8, 0, 0, 0, DateTimeKind.Local),
                            To = new DateTime(2025, 1, 19, 16, 0, 0, 0, DateTimeKind.Local),
                            WorkdayId = 2
                        },
                        new
                        {
                            Id = 4,
                            EmployeeId = "waiter-id-1",
                            From = new DateTime(2025, 1, 19, 8, 0, 0, 0, DateTimeKind.Local),
                            To = new DateTime(2025, 1, 19, 17, 30, 0, 0, DateTimeKind.Local),
                            WorkdayId = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
